from datetime import date
from decimal import Decimal
from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict


class InstrumentBase(BaseModel):
    """
    Foundational data representation for generic financial assets.
    """
    exchange: str = Field(..., description="Exchange venue name (e.g. NSE, NFO, NASDAQ)")
    segment: str = Field(..., description="Operational sub-segment block (e.g. NSE_EQ, NFO_OPT)")
    symbol: str = Field(..., description="Underlying core corporate symbol (e.g. RELIANCE, AAPL)")
    trading_symbol: str = Field(..., description="Explicit execution ticker identifier utilized during order placement")
    instrument_token: Optional[str] = Field(None, description="Abstract identification code generated by venue")
    isin: Optional[str] = Field(None, description="International Securities Identification Number")
    asset_type: str = Field(..., description="Asset classification matrix (e.g. EQUITY, FUTURE, OPTION)")
    expiry: Optional[date] = Field(None, description="Contract maturity date boundary")
    strike: Optional[Decimal] = Field(None, description="Contract exercise boundary price")
    option_type: Optional[str] = Field(None, description="Option tracking definition (e.g. CE, PE, CALL, PUT)")
    tick_size: Decimal = Field(Decimal("0.05"), description="Minimum step size variable for pricing units")
    lot_size: int = Field(1, description="Minimum order contract quantity packaging")
    currency: str = Field("INR", description="Base asset transaction currency code")
    is_active: bool = Field(True, description="System visibility active flag toggle")


class InstrumentCreate(InstrumentBase):
    """
    Schema for ingesting raw data assets during bulk morning sync cycles.
    """
    pass


class InstrumentUpdate(BaseModel):
    """
    Schema handling dynamic alterations or manual corporate action adjustments.
    """
    tick_size: Optional[Decimal] = None
    lot_size: Optional[int] = None
    is_active: Optional[bool] = None


class InstrumentResponse(InstrumentBase):
    """
    Data transfer object structuring serialized outbound metadata lookups.
    """
    id: int

    model_config = ConfigDict(from_attributes=True)


class InstrumentSearchFilter(BaseModel):
    """
    Input schema defining the search boundary matrices for user lookups.
    Includes sorting attributes to drive predictable, ordered client data grids.
    """
    q: Optional[str] = Field(None, description="Elastic wildcard string searching across trading_symbol and symbol fields")
    exchange: Optional[str] = Field(None, description="Filter parameters matching exchange boundaries exactly")
    segment: Optional[str] = Field(None, description="Filter parameters matching trading segment structures exactly")
    asset_type: Optional[str] = Field(None, description="Target specific security asset profiles")
    is_active: Optional[bool] = Field(True, description="Defaults search filters to active assets")
    
    # Sorting parameter vectors to handle high-volume data layout formatting
    sort_by: Optional[str] = Field("trading_symbol", description="Target field matrix for ordering results (e.g., trading_symbol, symbol, expiry)")
    sort_order: Optional[str] = Field("asc", description="Ordering sequence constraint. Allowed values: asc, desc")


class InstrumentPaginatedResponse(BaseModel):
    """
    Standard envelope format wrapping bulk contract search datasets.
    """
    items: List[InstrumentResponse]
    total_count: int
    page: int
    size: int