"""Locked F1 Basket strategy parameters — from basket_final_validation research."""

from __future__ import annotations

STRATEGY_NAME = "F1_BASKET_LOCKED_V1"

INITIAL_CAPITAL = 200_000.0
BASKET_SIZE = 12
PROFIT_TARGET_PCT = 0.12
HARD_STOP_PCT = 0.15
BUY_COST_PCT = 0.003
SELL_COST_PCT = 0.003

# Basket statuses
STATUS_DRAFT = "DRAFT"
STATUS_READY = "READY"
STATUS_NOT_READY = "NOT_READY"
STATUS_DEPLOYING = "DEPLOYING"
STATUS_ACTIVE = "ACTIVE"
STATUS_EXIT_PENDING = "EXIT_PENDING"
STATUS_EXITING = "EXITING"
STATUS_CLOSED = "CLOSED"
STATUS_FAILED = "FAILED"

PREVIEW_STATUSES = frozenset({STATUS_DRAFT, STATUS_READY})
OPERATIONAL_STATUSES = frozenset({STATUS_READY, STATUS_DEPLOYING, STATUS_ACTIVE})

BASKET_ENGINE = "F1_BASKET"
BROKER_ZERODHA = "zerodha"

# Constituent fill / deployment states
FILL_PENDING = "PENDING"
FILL_SUBMITTED = "SUBMITTED"
FILL_COMPLETE = "COMPLETE"
FILL_PARTIAL = "PARTIAL"
FILL_REJECTED = "REJECTED"
FILL_FAILED = "FAILED"
FILL_CANCELLED = "CANCELLED"
FILL_ADOPTED = "ADOPTED"

TERMINAL_FAILURE_STATUSES = frozenset({FILL_REJECTED, FILL_FAILED, FILL_CANCELLED})
NON_RESUBMIT_STATUSES = frozenset({FILL_SUBMITTED, FILL_COMPLETE, FILL_PARTIAL, FILL_ADOPTED})

SLOT_TARGET_EXPOSURE = INITIAL_CAPITAL / BASKET_SIZE

# Sell / exit
SELL_PENDING = "PENDING"
SELL_SUBMITTED = "SUBMITTED"
SELL_COMPLETE = "COMPLETE"
SELL_PARTIAL = "PARTIAL"
SELL_REJECTED = "REJECTED"
SELL_FAILED = "FAILED"
SELL_CANCELLED = "CANCELLED"

SELL_TERMINAL_FAILURE = frozenset({SELL_REJECTED, SELL_FAILED, SELL_CANCELLED})
SELL_NON_RESUBMIT = frozenset({SELL_SUBMITTED, SELL_COMPLETE, SELL_PARTIAL})

EXIT_REASON_TARGET = "TARGET"
EXIT_REASON_STOP = "STOP"
EXIT_REASON_MANUAL = "MANUAL"

MONITOR_INTERVAL_SEC = 300
